### ISSUE TITLE
Exception due to unauthorized stats command failure

### ISSUE THREAD

**Issue by DavisSylvester** [le-yams/nbmongo#37]
I am using Mongo 3.0.3 and your plugin with Auth enabled.  

When I attempt to connect to a db which requires auth it fails with the following error.  Access from the terminal with the same credentials work fine.

com.mongodb.CommandFailureException: { "serverUsed" : "127.0.0.1:27017" , "ok" : 0.0 , "errmsg" : "not authorized on admin to execute command { dbstats: true }" , "code" : 13}
	at com.mongodb.CommandResult.getException(CommandResult.java:76)
	at com.mongodb.CommandResult.throwOnError(CommandResult.java:140)
	at com.mongodb.DB.getStats(DB.java:477)
	at org.netbeans.modules.mongodb.ui.explorer.DBNode.createSheet(DBNode.java:110)
	at org.openide.nodes.AbstractNode.getSheet(AbstractNode.java:441)
	at org.openide.nodes.AbstractNode.getPropertySets(AbstractNode.java:457)
	at org.openide.nodes.FilterNode.getPropertySets(FilterNode.java:630)
	at org.openide.actions.PropertiesAction$DelegateAction.getPopupPresenter(PropertiesAction.java:194)
	at org.openide.util.Utilities.actionsToPopup(Utilities.java:1729)
	at org.openide.util.Utilities.actionsToPopup(Utilities.java:1815)
	at org.openide.explorer.view.TreeView.createPopup(TreeView.java:1058)
	at org.openide.explorer.view.TreeView$PopupAdapter.showPopup(TreeView.java:1555)
	at org.openide.awt.MouseUtils$PopupMouseAdapter.maybePopup(MouseUtils.java:189)
	at org.openide.awt.MouseUtils$PopupMouseAdapter.mouseReleased(MouseUtils.java:184)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by le-yams** [comment]
Hi Davis,

Actually this issue is not related to the authentication process. The plugin attempts to retrieve databases and collections stats (they are displayed in the properties windows according to the selected node in the explorer). To do so it run commands ("dbstats" in this case) but here it fails because your user profile doesn't have the privilege to do it. The failure is not properly handled and I'll try to fix this issue asap.

Regards,
Yann

**Comment by le-yams** [comment]
Hi Davis,
I have problems testing the fix. I'm no mongo admin and I don't know how to forbid the dbstats command usage. 
So I'm not able to recreate the issue conditions in order to formally validate the fix. Could you manually install the fixed version nbm ([see here](https://github.com/le-yams/nbmongo/releases/tag/nbmongo-8.1.3-rc1)) and tell me if the correction actually works ?

Regards,
Yann

**Comment by DavisSylvester** [comment]
Still getting same error.  Are you using the mongo java driver in your app.  I will try to take a look at your code this weekend to see if I can help.

I am a C# developer so not sure how much help I will be.

**Comment by le-yams** [comment]
That's weird, can you post the stacktrace of the error? If it's still exactly the same then you probably haven't properly installed the plugin fixed version.
If your interested to look at the code you must checkout the [8.1.x](https://github.com/le-yams/nbmongo/tree/v8.1.x) branch (not the master). Here is the [fix commit](https://github.com/le-yams/nbmongo/commit/009db69aac2dc5c8ee28398f22e11edc27e6f3cf).

Regards,
Yann

**Comment by le-yams** [comment]
Hi Davis,

I finally have been able to recreate the issue conditions so I enhanced the fix and released it.
The plugin update should be available soon in the IDE :)

Note that this fix is only about dbstats and collstats commands. There might be other issues related to mishandled unauthorized accesses.

Regards,
Yann
