### ISSUE TITLE
Exception expanding indexes in explorer

### ISSUE THREAD

**Issue by le-yams** [le-yams/nbmongo#38]
Exception expanding indexes in explorer

```
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
	at org.netbeans.modules.mongodb.indexes.Index.fromDBObject(Index.java:70)
	at org.netbeans.modules.mongodb.ui.explorer.IndexNodesFactory.createKeys(IndexNodesFactory.java:44)
	at org.openide.nodes.AsynchChildren.run(AsynchChildren.java:209)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

**Comment by le-yams** [comment]
Will be fixed by #32
