### ISSUE TITLE
ClassCastException when attempting to see the indexes of a collection.

### ISSUE THREAD

**Issue by Richard-Cranium** [le-yams/nbmongo#44]
I'm running mongoDB version 3.0.6 under OS X.  Netbeans 8.1

````
SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor org.openide.nodes.AsynchChildren                                                                                           │
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number                                                                                                                │
        at org.netbeans.modules.mongodb.indexes.Index.fromDBObject(Index.java:70)                                                                                                                │
        at org.netbeans.modules.mongodb.ui.explorer.IndexNodesFactory.createKeys(IndexNodesFactory.java:44)                                                                                      │
        at org.openide.nodes.AsynchChildren.run(AsynchChildren.java:209)                                                                                                                         │
        at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)                                                                                                                │
        at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)                                                                                                          │
        at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)                                                                                                                         │
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)      
````

**Comment by Richard-Cranium** [comment]
D'oh.  An obvious duplicate.  Sorry.
