### ISSUE TITLE
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number

### ISSUE THREAD

**Issue by markiewb** [le-yams/nbmongo#63]
```
Stacktrace: 
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
   at org.netbeans.modules.mongodb.indexes.Index.fromDBObject(Index.java:70)
   at org.netbeans.modules.mongodb.ui.explorer.IndexNodesFactory.createKeys(IndexNodesFactory.java:44)
   at org.openide.nodes.AsynchChildren.run(AsynchChildren.java:209)
   at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
   at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
   at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
```
https://netbeans.org/bugzilla/show_bug.cgi?id=257062

**Comment by le-yams** [comment]
Hi markiewb,

This stacktrace seems to indicate you are using an old version of the plugin. 
The NetBeans bugzilla seems down so I can't see the details of the issue. Would you give me the versions of the NetBeans and the nbmongo plugin you are using ?

Best Regards,
Yann

**Comment by markiewb** [comment]
@le-yams: I am not a user of your plugin. I saw the issue at bugzilla and reposted it here. So I cannot give you more details. If it has been already resolved, then it is fine. You can close the bugzilla issue as resolved fixed

**Comment by le-yams** [comment]
Ok, thanks for your input.

Best Regards,
Yann
