### ISSUE TITLE
Export option is not working

### ISSUE THREAD

**Issue by pedrohidalgo** [le-yams/nbmongo#67]
The Export Option is not working. It doesn't show the window, see stacktrace below:

java.util.MissingResourceException: Can't find resource for bundle org.openide.util.NbBundle$PBundle, key ExportVisualPanel1.filterLabel.text
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
	at org.openide.util.NbBundle.getMessage(NbBundle.java:642)
	at org.netbeans.modules.mongodb.ui.wizards.ExportVisualPanel1.initComponents(ExportVisualPanel1.java:128)
	at org.netbeans.modules.mongodb.ui.wizards.ExportVisualPanel1.<init>(ExportVisualPanel1.java:40)
	at org.netbeans.modules.mongodb.ui.wizards.ExportWizardPanel1.getComponent(ExportWizardPanel1.java:50)
	at org.netbeans.modules.mongodb.ui.wizards.ExportWizardPanel1.getComponent(ExportWizardPanel1.java:33)
	at org.netbeans.modules.mongodb.ui.wizards.ExportWizardAction.actionPerformed(ExportWizardAction.java:79)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by le-yams** [comment]
Hi Pedro,

Thank you for reporting this issue, I'll fix it asap.

Regards,
Yann

**Comment by le-yams** [comment]
I just published a release fixing this issue. It will be available as soon as the NetBeans team validates the plugin.
With my apologies for the delay.

Best Regards,
Yann

**Comment by Kuzdo** [comment]
Hi @le-yams.
This fix is breaking the plugin. Plugin are no more listed on Services tab.

**Comment by le-yams** [comment]
Hi @Kuzdo,

Thank you very much for signaling it to me, Indeed the nbm was not correctly built, 
I've just re-uploaded it and it will be available as soon as the NetBeans team validates the plugin.

I'm truly sorry for the inconvenience.

Best regards,
Yann

**Comment by paul-court** [comment]
Can we grab the nbm from somewhere?

**Comment by le-yams** [comment]
@gargoyle yes, I updated the attached nbm on the [release page](https://github.com/le-yams/nbmongo/releases/tag/nbmongo-8.2.4NB82).
You can also download it directly on the [NBMongo plugin portal page](http://plugins.netbeans.org/plugin/52638/nbmongo)

**Comment by paul-court** [comment]
Ahh. Thanks! :-)
